[project]
name = "binance-etl"
version = "0.1.0"
description = "Binance ETL Pipeline."
readme = "README.md"
authors = [
    { name = "njuedominic", email = "nmd.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
binance-etl = "binance_etl:main"

[tool.uv]
package = false
